### ISSUE TITLE
[BUG]: Can you fix please? Dosen't work

### ISSUE THREAD

**Issue by enric34** [nogiszd/xiaomi-note-exporter#12]
Can you fix please? Dosen't 
![2023-08-27_22-32-10](https://github.com/nogiszd/xiaomi-note-exporter/assets/35368222/55d4ed43-c673-4591-b78c-239463212072)
work

**Comment by enric34** [comment]
https://stackoverflow.com/questions/60296873/sessionnotcreatedexception-message-session-not-created-this-version-of-chrome

**Comment by nogiszd** [comment]
Hi @enric34,
what version of app are you using? Is it the latest one?

**Comment by nogiszd** [comment]
The same behaviour was described in [this issue](https://github.com/nogiszd/xiaomi-note-exporter/issues/13).
Please download latest version as mentioned in the issue above.
Let me know if this have resolved the case. Thanks.

**Comment by nogiszd** [comment]
Issue have been resolved, no response from submitter.
