### ISSUE TITLE
[BUG]: Command line crashes as soon as it opens

### ISSUE THREAD

**Issue by NabMrBombastic** [nogiszd/xiaomi-note-exporter#13]
hello,command line crashes as soon as it opens

i have net framework 7.0 tried all 6.x versions

**Comment by nogiszd** [comment]
Hi @NabMrBombastic, 
are you using latest version?

**Comment by NabMrBombastic** [comment]
Yes

Στις Τρί 29 Αυγ 2023, 18:16 ο χρήστης Dawid ***@***.***>
έγραψε:

**Comment by nogiszd** [comment]
Indeed, dependencies were outdated. [Latest release](https://github.com/nogiszd/xiaomi-note-exporter/releases/tag/v1.1.2) fixes that.

Please confirm if this resolved the issue. Thanks.

**Comment by NabMrBombastic** [comment]
> Indeed, dependencies were outdated. [Latest release](https://github.com/nogiszd/xiaomi-note-exporter/releases/tag/v1.1.2) fixes that.
> 
> Please confirm if this resolved the issue. Thanks.

Now I went further than before but no,still doesn't work .

I uploaded vid on gofile if you want to see  https://gofile.io/d/ZQML5D

**Comment by nogiszd** [comment]
I can see you input domain name, but it is the same as the default one, so you can skip this step by simply clicking the return (enter) key. 

On the other hand, if you have to input domain manually, you need to do it without protocol prefix and without slashes after.

Example: „google.com” **not** „https://google.com”

Let me know if you succeeded.

**Comment by NabMrBombastic** [comment]
Thank you,it workedd

**Comment by nogiszd** [comment]
Closing the issue, as it is solved.

**Comment by shady266** [comment]
Well, I already got the md file, but I am stuck at this step. I do not understand it. Can you explain to me what I should do?
![Screenshot 2023-11-24 013233](https://github.com/nogiszd/xiaomi-note-exporter/assets/151885425/b927ddf5-3560-4713-a962-51a9e782bf6d)
