### ISSUE TITLE
[FEATURE]: 

### ISSUE THREAD

**Issue by NabMrBombastic** [nogiszd/xiaomi-note-exporter#15]
It would be nice if the exported md file could be imported in Google notes somehow and the notes actually showing all in different notes just like on mi cloud. 

Right now they show all together in the md file the only way is to copy them all into Google but who would want them all together in one note?

**Comment by nogiszd** [comment]
Hi! 
There is an ongoing pull request (#14) which implements this feature.
More details are in pull request's comments.

There are near future plans to rewrite whole app with GUI and implement described above features.

**Comment by NabMrBombastic** [comment]
I guess I'll just wait for your update,i'm too noob for this unfortunately 

I'm using google keep which doesn't even have import option

Thank you,I'll wait

**Comment by nogiszd** [comment]
No problem, I will inform you in this thread about the update.

**Comment by NabMrBombastic** [comment]
Did the feature got added?

**Comment by nogiszd** [comment]
Unfortunately, not yet. I didn't have much free time to work on it. 
I am currently busy with private matters and I don't know when it will be finished.

I can only tell that, these features will be implemented with GUI. All progress is stored on [separate branch](https://github.com/nogiszd/xiaomi-note-exporter/tree/feature/gui).

**Comment by NabMrBombastic** [comment]
Any news?

**Comment by nogiszd** [comment]
Unfortunately, I don't have much time to maintain this project [as stated in README](https://github.com/nogiszd/xiaomi-note-exporter?tab=readme-ov-file#-maintenance-mode). 
If I will have any free time, then I will probably continue with the GUI version. But for now, no ETA.

**Comment by nogiszd** [comment]
Future updates will be present in separate branches.
