### ISSUE TITLE
[BUG]: Well, I already got the md file, but I am stuck at this step. I do not understand it. Can you explain to me what I should do?

### ISSUE THREAD

**Issue by shady266** [nogiszd/xiaomi-note-exporter#16]
![Screenshot 2023-11-24 013233](https://github.com/nogiszd/xiaomi-note-exporter/assets/151885425/222b47af-1111-446f-a049-704a65f8467b)

**Comment by nogiszd** [comment]
There is an splitting feature awaiting in pull requests.
