### ISSUE TITLE
[BUG]: Software broken (Unhandled exception. OpenQA.Selenium.WebDriverTimeoutException: Timed out after 10 seonds)

### ISSUE THREAD

**Issue by GlitchedCod** [nogiszd/xiaomi-note-exporter#20]
Hi !

Thank you for this very useful tools (I got like 100 notes on this app !) but it doesn't seems to work anymore, which is a problem since you don't actively develop it now. If you need more help and test on my side we can PM.

**Describe the bug**
The software seems to be broken now, I've tried the version 1.2.1 and the 1.2.0 and I got the same crash. I've reinstalled .NET Desktop Runtime with just the Runtime too but same effect.

**To Reproduce**
1. Start the xiaomiNoteExporter.exe
2. Connect to us.i.mi.com with the "Chrome for Testing"
3. Click on "Notes"
4. Connect with SMS 2FA (without clicking on the menu on the Note app and log-in with the 2FA the terminal says "Not connected, the app will close")
5. Get inside the Note webapp
6. Press a key on the terminal to validate us.i.mi.com / also tested with just i.mi.com
7. I got a crash after 10 seconds

**Screenshots**
![image](https://github.com/nogiszd/xiaomi-note-exporter/assets/44437316/dd7625a2-609b-4b8c-bd38-077aa78a914b)
Unhandled exception. OpenQA.Selenium.WebDriverTimeoutException: Timed out after 10 seonds

**Current environment (please complete the following information):**
Windows 11 Home x64
NET Framework Runtime 6.0.28 x64

**Additional context**
I am French so my account is in french and the website seems to be just i.mi.com and not us.i.mi.com like suggested by the app, even with i.mi.com I got the same error.

**Comment by nogiszd** [comment]
Hi, please let me know if previous version (1.2.0) works fine. 
It might be that update of libraries caused some issues.

**Comment by GlitchedCod** [comment]
> Hi, please let me know if previous version (1.2.0) works fine. It might be that update of libraries caused some issues.

Like I said I've also tested the 1.2.0 version (I've read the changelog and I also wanted to be sure that the libraries didn't broke anything) and I still get the same issue.

**Comment by GlitchedCod** [comment]
Ok so you can close this issue.
It worked onto another computer, not sure why though. I got a backup of 208 notes ! This is so much better now but I'm a bit lost for the next step since I wanted to import all of this directly into Quillpad and that it doesn't seems possible.
Thanks for this small tool, amazing work.
