### ISSUE TITLE
[BUG]: Text is not inserted 

### ISSUE THREAD

**Issue by Lola019-oss** [nogiszd/xiaomi-note-exporter#23]
**Describe the bug**
Hello! Now I'm trying to insert a token into the application with the command CTRL + V, but nothing happens except that it is only inserted ▿V

**To Reproduce**
1. Launching an application on a laptop 
2. Click on CTRL + V
3. See ▿v

**Comment by nogiszd** [comment]
I've tested it with Windows Terminal and I don't see any problem.
It might be that your terminal doesn't support this paste shortcut. 

Other shortcut that are supported in many terminals are: `SHIFT` + `INSERT` or `CTRL` + `SHIFT` + `V`.
For me even clicking right mouse button does the trick.

**Comment by Lola019-oss** [comment]
> Hi. I've tested it with Windows Terminal and I don't see any problem.
> It might be that your terminal doesn't support this paste shortcut. 
> 
> Other shortcut that are supported in many terminals are: `SHIFT` + `INSERT` or `CTRL` + `SHIFT` + `V`.
> For me even clicking right mouse button does the trick.
> 
> So this isn't a program issue, rather a terminal's in which program executes.

Thank you!

**Comment by Lola019-oss** [comment]
> Hi. I've tested it with Windows Terminal and I don't see any problem.
> It might be that your terminal doesn't support this paste shortcut. 
> 
> Other shortcut that are supported in many terminals are: `SHIFT` + `INSERT` or `CTRL` + `SHIFT` + `V`.
> For me even clicking right mouse button does the trick.
> 
> So this isn't a program issue, rather a terminal's in which program executes.

Thank you!
