### ISSUE TITLE
[BUG]: cmd window closes as soon as the progress percentage shows up

### ISSUE THREAD

**Issue by donperawn** [nogiszd/xiaomi-note-exporter#6]
Everything ok after putting in the nessesary values but as soon as it starts to load up my notes the cmd files closes
edit1: I have a suspicion that the mind map type notes are what's fucking it up. Im deleting all of those and wil update you
edit2: no it wasnt that

**Comment by nogiszd** [comment]
[Latest release](https://github.com/nogiszd/xiaomi-note-exporter/releases/latest) fixes that issue.
